{%/%    perc.alpha.core/%
 %/%%   perc.alpha.core/%%
 %/%%%  perc.alpha.core/%%%
 %/$    perc.alpha.core/$
 %/$$   perc.alpha.core/$$
 %/$$$  perc.alpha.core/$$$
 %/?    perc.alpha.core/?
 %/??   perc.alpha.core/??
 %/???  perc.alpha.core/???}
